apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: kube-copilot-agent
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kube-copilot-agent
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: kube-copilot-agent
  ports:
  - name: webhook
    port: 8090
    targetPort: 8090
    protocol: TCP
